### ISSUE TITLE
Installing 0.6.4 from PyPI does not include stable_difussion inside models folder

### ISSUE THREAD

**Issue by jonbesga** [keras-team/keras-cv#2072]
### Current Behavior:

`pip install keras-cv` to install latest version 0.6.4

Try to use anything related to stable diffusion like the tokenizer:

`tokenizer = keras_cv.models.stable_diffusion.SimpleTokenizer()`

It will complain with `AttributeError: module 'keras_cv.models' has no attribute 'stable_diffusion'`

Note that it works if I decide to do the following import `keras_cv.src.models.stable_diffusion.SimpleTokenizer()` where I use the `src` folder

### Expected Behavior:

Import works correctly

**Comment by jbischof** [comment]
Thanks @jonbesga!

Has it worked in other versions or you just noticed now? If the former, please let us know which version.

**Comment by aliftadvantage** [comment]
Having the same issue. Was working in v0.6.1

Repro:
Working in v0.6.1 - https://colab.research.google.com/drive/1brn2BhoRhr8LJ7_daB-F7Z_4Lq5bLAVi?usp=sharing
Not working in v0.6.2 - https://colab.research.google.com/drive/1QgHiHTQ44fNnOzags5dxsN5Q3pG3PtxM?usp=sharing

**Comment by jbischof** [comment]
@aliftadvantage the colabs above aren't quite right because you never `import keras_cv`. However, I was able to replicate the bug after the import ([colab](https://colab.sandbox.google.com/gist/jbischof/5b0da53d63c7aa8f48c1e2ad5a86aeda/copy-of-stable-diffusion-pip-install-v0-6-2.ipynb#scrollTo=s2hgNoFtZIGA)).

@ianstenbit I don't see this error in my local dev environment. Could it be related to the new `namex` export system?

**Comment by ianstenbit** [comment]
This is caused by the fact that the non-top level components of StableDiffusion don't have `@keras_cv_export` tags on them.

They can be imported in the newer versions under `keras_cv.src.models.stable_diffusion`, and we can include a `@keras_cv_export` tag for them if we'd like to export them directly.

**Comment by jbischof** [comment]
Interesting. I wonder if we should leave a note in our README because `namex` is very new and there is no `src` folder in our codebase to even hint at this.

**Comment by ianstenbit** [comment]
> Interesting. I wonder if we should leave a note in our README because `namex` is very new and there is no `src` folder in our codebase to even hint at this.

We can also just export these symbols if we want, as it's clear that people are using them!

**Comment by aliftadvantage** [comment]
> We can also just export these symbols if we want, as it's clear that people are using them!

+1! E.g. it uses them in the keras fine-tuning stable diffusion guide: https://keras.io/examples/generative/finetune_stable_diffusion/

**Comment by ianstenbit** [comment]
> > We can also just export these symbols if we want, as it's clear that people are using them!
> 
> +1! For example, it uses them in the keras fine-tuning stable diffusion guide: https://keras.io/examples/generative/finetune_stable_diffusion/

Ahh yes -- let's include these then! If anyone would like to send a PR I will review it ASAP -- otherwise I'll send a fix tomorrow.
